services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: graduation_app

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8085:8080
